// <auto-generated />
using DemoWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoWeb.Migrations
{
    [DbContext(typeof(CategoryDbContext))]
    [Migration("20241031024129_hehee")]
    partial class hehee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoWeb.Models.Category", b =>
                {
                    b.Property<int>("Ma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ma"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Ma");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Ma = 1,
                            Description = " Tím",
                            Name = "Khoai"
                        },
                        new
                        {
                            Ma = 2,
                            Description = " Tím",
                            Name = "Sắn"
                        },
                        new
                        {
                            Ma = 3,
                            Description = " Tím",
                            Name = "Ngô"
                        },
                        new
                        {
                            Ma = 4,
                            Description = " Tím",
                            Name = "Bắp"
                        },
                        new
                        {
                            Ma = 5,
                            Description = " Tím",
                            Name = "Dưa hấu"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
